apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: polymer2parquet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: us-central1-docker.pkg.dev/polymer2parquet/polymer2parquet/polymer2parquet-backend:latest
          envFrom:
            - configMapRef:
                name: polymer2parquet-config
            - secretRef:
                name: polymer2parquet-secrets
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /api/players/
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/players/
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"