# Generated by Django 6.0.5 on 2026-05-20 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0005_alter_player_position'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Championship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_year', models.IntegerField()),
                ('league', models.CharField(choices=[('NBA', 'NBA'), ('ABA', 'ABA')], default='NBA', max_length=3)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='championships', to='teams.team')),
            ],
            options={
                'ordering': ['season_year'],
                'unique_together': {('season_year', 'league')},
            },
        ),
        migrations.CreateModel(
            name='PlayerChampionship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_championships', to='championships.championship')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='championships', to='players.player')),
            ],
            options={
                'unique_together': {('player', 'championship')},
            },
        ),
    ]
