# Generated by Django 6.0.5 on 2026-06-09 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0005_alter_player_position'),
        ('teams', '0002_team_successor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerIdentityMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=20)),
                ('external_id', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_mappings', to='players.player')),
            ],
            options={
                'ordering': ['source', 'player__last_name', 'player__first_name'],
            },
        ),
        migrations.CreateModel(
            name='CurrentSeasonStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_year', models.IntegerField(default=2026)),
                ('league', models.CharField(default='NBA', max_length=3)),
                ('games_played', models.IntegerField(default=0)),
                ('minutes_per_game', models.FloatField(blank=True, null=True)),
                ('points_per_game', models.FloatField(blank=True, null=True)),
                ('rebounds_per_game', models.FloatField(blank=True, null=True)),
                ('assists_per_game', models.FloatField(blank=True, null=True)),
                ('steals_per_game', models.FloatField(blank=True, null=True)),
                ('blocks_per_game', models.FloatField(blank=True, null=True)),
                ('turnovers_per_game', models.FloatField(blank=True, null=True)),
                ('field_goal_percentage', models.FloatField(blank=True, null=True)),
                ('three_point_percentage', models.FloatField(blank=True, null=True)),
                ('free_throw_percentage', models.FloatField(blank=True, null=True)),
                ('plays_today', models.BooleanField(default=False)),
                ('in_progress', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_season', to='players.player')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_season', to='teams.team')),
            ],
            options={
                'ordering': ['player', 'team'],
                'unique_together': {('player', 'season_year')},
            },
        ),
    ]
