# Generated by Django 6.0.4 on 2026-04-09 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('position', models.CharField(blank=True, choices=[('PG', 'Point Guard'), ('SG', 'Shooting Guard'), ('SF', 'Small Forward'), ('PF', 'Power Forward'), ('C', 'Center')], max_length=2)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('college', models.CharField(blank=True, max_length=100)),
                ('height_inches', models.IntegerField(blank=True, null=True)),
                ('weight_lbs', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_type', models.CharField(choices=[('MVP', 'Most Valuable Player'), ('DPOY', 'Defensive Player of the Year'), ('ROY', 'Rookie of the Year'), ('MIP', 'Most Improved Player'), ('6MOY', 'Sixth Man of the Year'), ('ALL_NBA_1', 'All-NBA First Team'), ('ALL_NBA_2', 'All-NBA Second Team'), ('ALL_NBA_3', 'All-NBA Third Team'), ('ALL_STAR', 'All-Star Selection'), ('CHAMP', 'Championship'), ('ALL_ABA_1', 'All-ABA First Team'), ('ALL_ABA_2', 'All-ABA Second Team'), ('ABA_MVP', 'ABA Most Valuable Player'), ('ABA_ROY', 'ABA Rookie of the Year')], max_length=20)),
                ('season_year', models.IntegerField()),
                ('league', models.CharField(choices=[('NBA', 'NBA'), ('ABA', 'ABA')], default='NBA', max_length=3)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='players.player')),
            ],
            options={
                'ordering': ['season_year', 'award_type'],
            },
        ),
    ]
