# Generated by Django 6.0.4 on 2026-04-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_player_player_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='award_type',
            field=models.CharField(choices=[('MVP', 'Most Valuable Player'), ('DPOY', 'Defensive Player of the Year'), ('ROY', 'Rookie of the Year'), ('MIP', 'Most Improved Player'), ('6MOY', 'Sixth Man of the Year'), ('ALL_NBA_1', 'All-NBA First Team'), ('ALL_NBA_2', 'All-NBA Second Team'), ('ALL_NBA_3', 'All-NBA Third Team'), ('ALL_DEF_NBA_1', 'All-Defense NBA First Team'), ('ALL_DEF_NBA_2', 'All-Defense NBA Second Team'), ('ALL_STAR', 'All-Star Selection'), ('CHAMP', 'Championship'), ('ALL_ABA_1', 'All-ABA First Team'), ('ALL_ABA_2', 'All-ABA Second Team'), ('ALL_DEF_ABA_1', 'All-Defense ABA First Team'), ('ABA_MVP', 'ABA Most Valuable Player'), ('ABA_ROY', 'ABA Rookie of the Year')], max_length=20),
        ),
    ]
