apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: polymer2parquet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          envFrom:
            - configMapRef:
                name: polymer2parquet-config
            - secretRef:
                name: polymer2parquet-secrets
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - polymer2parquetuser
                - -d
                - polymer2parquetdb
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc