---
- name: Run data ingestion on GKE
  hosts: local
  connection: local
  vars:
    k8s_namespace: polymer2parquet

  tasks:
    - name: Get backend pod name
      shell: |
        kubectl get pod \
          -n {{ k8s_namespace }} \
          -l app=backend \
          -o jsonpath='{.items[0].metadata.name}'
      register: backend_pod

    - name: Run load_teams
      shell: |
        kubectl exec -n {{ k8s_namespace }} {{ backend_pod.stdout }} \
          -- python manage.py load_teams 2>&1
      register: load_teams_output

    - name: Print load_teams output
      debug:
        msg: "{{ load_teams_output.stdout_lines }}"

    - name: Run load_players
      shell: |
        kubectl exec -n {{ k8s_namespace }} {{ backend_pod.stdout }} \
          -- python manage.py load_players 2>&1
      register: load_players_output

    - name: Print load_players output
      debug:
        msg: "{{ load_players_output.stdout_lines }}"

    - name: Run load_seasons
      shell: |
        kubectl exec -n {{ k8s_namespace }} {{ backend_pod.stdout }} \
          -- python manage.py load_seasons 2>&1
      register: load_seasons_output

    - name: Print load_seasons output
      debug:
        msg: "{{ load_seasons_output.stdout_lines }}"

    - name: Run load_awards
      shell: |
        kubectl exec -n {{ k8s_namespace }} {{ backend_pod.stdout }} \
          -- python manage.py load_awards 2>&1
      register: load_awards_output

    - name: Print load_awards output
      debug:
        msg: "{{ load_awards_output.stdout_lines }}"

    - name: Run set_franchise_successors
      shell: |
        kubectl exec -n {{ k8s_namespace }} {{ backend_pod.stdout }} \
          -- python manage.py set_franchise_successors 2>&1
      register: set_franchise_successors_output

    - name: Print set_franchise_successors output
      debug:
        msg: "{{ set_franchise_successors_output.stdout_lines }}"

    - name: Run load_championships
      shell: |
        kubectl exec -n {{ k8s_namespace }} {{ backend_pod.stdout }} \
          -- python manage.py load_championships 2>&1
      register: load_championships_output

    - name: Print load_championships output
      debug:
        msg: "{{ load_championships_output.stdout_lines }}"

    - name: Run load_player_championships
      shell: |
        kubectl exec -n {{ k8s_namespace }} {{ backend_pod.stdout }} \
          -- python manage.py load_player_championships 2>&1
      register: load_player_championships_output

    - name: Print load_player_championships output
      debug:
        msg: "{{ load_player_championships_output.stdout_lines }}"