# Generated by Django 6.0.4 on 2026-04-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=5)),
                ('league', models.CharField(choices=[('NBA', 'NBA'), ('ABA', 'ABA')], default='NBA', max_length=3)),
                ('founded', models.IntegerField(blank=True, null=True)),
                ('disbanded', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('previous_name', models.CharField(blank=True, max_length=100)),
                ('previous_city', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['league', 'city', 'name'],
            },
        ),
    ]
