# Generated by Django 6.0.4 on 2026-04-09 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_year', models.IntegerField()),
                ('league', models.CharField(choices=[('NBA', 'NBA'), ('ABA', 'ABA')], default='NBA', max_length=3)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('games_played', models.IntegerField(default=0)),
                ('games_started', models.IntegerField(default=0)),
                ('minutes_per_game', models.FloatField(blank=True, null=True)),
                ('points_per_game', models.FloatField(blank=True, null=True)),
                ('rebounds_per_game', models.FloatField(blank=True, null=True)),
                ('assists_per_game', models.FloatField(blank=True, null=True)),
                ('steals_per_game', models.FloatField(blank=True, null=True)),
                ('blocks_per_game', models.FloatField(blank=True, null=True)),
                ('turnovers_per_game', models.FloatField(blank=True, null=True)),
                ('field_goal_percentage', models.FloatField(blank=True, null=True)),
                ('three_point_percentage', models.FloatField(blank=True, null=True)),
                ('free_throw_percentage', models.FloatField(blank=True, null=True)),
                ('player_efficiency_rating', models.FloatField(blank=True, null=True)),
                ('true_shooting_percentage', models.FloatField(blank=True, null=True)),
                ('win_shares', models.FloatField(blank=True, null=True)),
                ('box_plus_minus', models.FloatField(blank=True, null=True)),
                ('value_over_replacement', models.FloatField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='players.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='teams.team')),
            ],
            options={
                'ordering': ['player', 'season_year'],
                'unique_together': {('player', 'team', 'season_year', 'league')},
            },
        ),
    ]
